### ISSUE TITLE
Auth Error 

### ISSUE THREAD

**Issue by scorpius** [manwhoami/FindMyiPhone#3]
I was getting this error with your script. Then I tried https://github.com/picklepete/pyicloud and it worked, but I did get a notification email. Does your method bypass the notification via the User-Agent string?

**Comment by manwhoami** [comment]
My script works through a different mechanism than PyiCloud. PyiCloud recreates the traffic flow that occurs when you visit iCloud.com in a web browser (which will notify the user that their account has been accessed). My script recreates the traffic that occurs when you use the FindMyiPhone App on iOS. The FMIP App does not notify the user or send an email, so that is how my script is able to bypass.

Are you sure that you are entering your credentials properly? Do you have 2 factor authentication (2FA) enabled? (That shouldn't matter, but just so we have an idea as to what is going on). Are you using an auth token and DSID, or a username (bob@icloud.com) and password?

**Comment by scorpius** [comment]
The credentials are correct, 2FA is disabled, and I'm using my email and password.

**Comment by scorpius** [comment]
It works now. I didn't have icloud setup properly. You can close this issue.

**Comment by manwhoami** [comment]
Glad to hear. Thanks for the report.
